// packages/demo-react/src/Details.tsx
import {
  detailRows,
  elementNet,
  formatValue,
  isElementId,
  kindLabel,
  label,
  summary,
} from '@boardui/demo-shared';
import type { BoardViewerElement, ElementInfo } from '@boardui/react';
import type { ReactNode } from 'react';
import type { BoardUi, Tag } from './board-ui.js';

/** The selected element's metadata, with links to its net, pin and component. */
export function Details({
  viewer,
  ui,
}: {
  viewer: () => BoardViewerElement;
  ui: BoardUi;
}): ReactNode {
  const info = ui.selection;
  if (!info) return <div id="details" className="details" hidden />;
  const { title, detail } = summary(info);
  const net = elementNet(info);
  const tag = ui.tags.find((t) => t.info.id === info.id);
  const value = (key: string, v: unknown) =>
    isElementId(v) ? (
      <button type="button" className="link" onClick={() => ui.select(v, true)}>
        {label(v)}
      </button>
    ) : (
      formatValue(key, v)
    );
  return (
    <div id="details" className="details">
      <header>
        <span className={`badge kind-${info.kind}`}>{kindLabel(info.kind)}</span>
        <strong className="details-title">{title}</strong>
        <button
          type="button"
          className="remove"
          title="Clear selection (Esc)"
          onClick={() => ui.select(null)}
        >
          ×
        </button>
      </header>
      {detail && <div className="muted details-sub">{detail}</div>}
      <dl className="facts">
        {detailRows(info).map(([k, v]) => [
          <dt key={`${k}:dt`}>{k}</dt>,
          <dd key={`${k}:dd`}>{value(k, v)}</dd>,
        ])}
      </dl>
      <div className="button-row">
        <button type="button" onClick={() => viewer().focus(info.id)}>
          Focus
        </button>
        {isElementId(net) && (
          <button type="button" onClick={() => ui.toggleHighlight(net)}>
            {ui.highlights.some((h) => h.net === net) ? 'Unhighlight net' : 'Highlight net'}
          </button>
        )}
        {tag && (
          <button type="button" onClick={() => ui.togglePin(info.id)}>
            {tag.pinned ? 'Unpin tag' : 'Pin tag'}
          </button>
        )}
      </div>
    </div>
  );
}

/** A tag's content (the widget around it follows its element). */
export function TagCard({ tag, ui }: { tag: Tag; ui: BoardUi }): ReactNode {
  const { info, pinned } = tag;
  const { title, detail } = summary(info);
  return (
    <div className={`tag kind-${info.kind}${pinned ? ' pinned' : ''}`} data-id={info.id}>
      <button type="button" className="tag-body" onClick={() => ui.select(info.id)}>
        <b>{title}</b>
        {detail && <span>{detail}</span>}
      </button>
      <button
        type="button"
        className="tag-close"
        title="Remove tag"
        onClick={() => ui.removeTag(info.id)}
      >
        ×
      </button>
    </div>
  );
}

/** The hover tooltip's content. */
export function TooltipContent({ info }: { info: ElementInfo }): ReactNode {
  const { title, detail } = summary(info);
  return (
    <>
      <strong>{title}</strong>
      {detail && <span>{detail}</span>}
    </>
  );
}

// packages/demo-angular/src/app/details.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import {
  detailRows,
  elementNet,
  formatValue,
  isElementId,
  kindLabel,
  label,
  summary,
} from '@boardui/demo-shared';
import { BoardUi, type Tag } from './board-ui';
import { viewer } from './session';

/** The selected element's metadata, with links to its net, pin and component. */
@Component({
  selector: 'div[app-details]',
  host: { id: 'details', class: 'details', '[hidden]': '!ui.selection()' },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (view(); as v) {
      <header>
        <span [class]="'badge kind-' + v.info.kind">{{ v.kind }}</span>
        <strong class="details-title">{{ v.title }}</strong>
        <button type="button" class="remove" title="Clear selection (Esc)" (click)="ui.select(null)">×</button>
      </header>
      @if (v.detail) {
        <div class="muted details-sub">{{ v.detail }}</div>
      }
      <dl class="facts">
        @for (row of v.rows; track $index) {
          <dt>{{ row.key }}</dt>
          <dd>
            @if (row.link; as id) {
              <button type="button" class="link" (click)="ui.select(id, true)">{{ row.text }}</button>
            } @else {
              {{ row.text }}
            }
          </dd>
        }
      </dl>
      <div class="button-row">
        <button type="button" (click)="focus(v.info.id)">Focus</button>
        @if (v.net; as net) {
          <button type="button" (click)="ui.toggleHighlight(net)">{{ highlighted() ? 'Unhighlight net' : 'Highlight net' }}</button>
        }
        @if (tag(); as tag) {
          <button type="button" (click)="ui.togglePin(v.info.id)">{{ tag.pinned ? 'Unpin tag' : 'Pin tag' }}</button>
        }
      </div>
    }
  `,
})
export class Details {
  protected readonly ui = inject(BoardUi);
  protected readonly view = computed(() => {
    const info = this.ui.selection();
    if (!info) return null;
    const net = elementNet(info);
    return {
      info,
      ...summary(info),
      kind: kindLabel(info.kind),
      net: isElementId(net) ? net : null,
      rows: detailRows(info).map(([key, value]) =>
        isElementId(value)
          ? { key, link: value, text: label(value) }
          : { key, link: null, text: formatValue(key, value) },
      ),
    };
  });
  protected readonly highlighted = computed(() => {
    const net = this.view()?.net;
    return this.ui.highlights().some((h) => h.net === net);
  });
  protected readonly tag = computed(() => {
    const id = this.ui.selection()?.id;
    return this.ui.tags().find((t) => t.info.id === id);
  });

  protected focus(id: string): void {
    viewer().focus(id);
  }
}

/** A tag's content (the widget around it follows its element). */
@Component({
  selector: 'div[app-tag]',
  host: {
    '[class]': "'tag kind-' + tag().info.kind + (tag().pinned ? ' pinned' : '')",
    '[attr.data-id]': 'tag().info.id',
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button type="button" class="tag-body" (click)="ui.select(tag().info.id)">
      <b>{{ text().title }}</b>
      @if (text().detail) {
        <span>{{ text().detail }}</span>
      }
    </button>
    <button type="button" class="tag-close" title="Remove tag" (click)="ui.removeTag(tag().info.id)">×</button>
  `,
})
export class TagCard {
  readonly tag = input.required<Tag>();
  protected readonly ui = inject(BoardUi);
  protected readonly text = computed(() => summary(this.tag().info));
}
