// packages/demo-angular/src/app/landing.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import {
  formatBytes,
  SAMPLE_GROUPS,
  SAMPLES,
  type Sample,
  sampleLabel,
  TEST_CASES,
  TEST_CASES_PAGE,
  testCasePath,
  testCaseUrl,
} from '@boardui/demo-shared';
import { SAMPLE_SIZES } from '@boardui/demo-shared/sizes';

const size = (path: string) => formatBytes(SAMPLE_SIZES[path] ?? 0);

/** The top bar's sample picker. */
@Component({
  selector: 'label[app-sample-picker]',
  host: { class: 'sample-picker' },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="sr-only">Sample board</span>
    <select id="sample-select" aria-label="Sample board" (change)="pick($event)">
      <option value="">Samples…</option>
      @for (group of groups; track group.name) {
        <optgroup [label]="group.name">
          @for (sample of group.samples; track sample.id) {
            <option [value]="sample.id">{{ sample.label }}</option>
          }
        </optgroup>
      }
    </select>
  `,
})
export class SamplePicker {
  readonly open = output<Sample>();

  protected readonly groups = SAMPLE_GROUPS.map((name) => ({
    name,
    samples: SAMPLES.filter((s) => s.group === name).map((s) => ({
      id: s.id,
      label: sampleLabel(s, SAMPLE_SIZES),
    })),
  }));

  protected pick(event: Event): void {
    const select = event.target as HTMLSelectElement;
    const sample = SAMPLES.find((s) => s.id === select.value);
    select.value = '';
    if (sample) this.open.emit(sample);
  }
}

/** A sample on the landing page: a card, or a chip for the hand-written ones. */
@Component({
  selector: 'button[app-sample-card]',
  host: {
    type: 'button',
    '[class]': "featured() ? 'sample-card' : 'sample-chip'",
    '[attr.data-sample]': 'sample().id',
    '[title]': 'sample().description',
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="sample-group">{{ sample().group }}</span>
    <span class="sample-name">{{ sample().name }}</span>
    @if (featured()) {
      <span class="sample-desc">{{ sample().description }}</span>
    }
    <span class="sample-size">{{ size() }}</span>
  `,
})
export class SampleCard {
  readonly sample = input.required<Sample>();
  protected readonly featured = computed(() => this.sample().group !== 'Hand-written');
  protected readonly size = computed(() => size(this.sample().xml));
}

/** The empty state: drop zone, samples, and links to the IPC consortium test cases. */
@Component({
  selector: 'div[app-landing]',
  host: { id: 'empty', class: 'empty' },
  imports: [SampleCard],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="hero">
      <img src="logo.svg" alt="" width="72" height="72" />
      <h1>Printed circuit boards in 3D</h1>
      <p class="lead">
        Drop an <strong>IPC-2581</strong> file to convert it to a glTF board and explore its
        components, pins and nets. Conversion runs locally in WebAssembly: your file isn’t
        uploaded. 3D models of KiCad library parts are fetched from gitlab.com by footprint name.
      </p>
      <button id="drop-zone" class="drop-zone" type="button" (click)="pickFile.emit()">
        <span class="drop-title">Drop a file here, or click to choose one</span>
        <span class="drop-hint">IPC-2581 <code>.xml</code>, a boardui <code>.glb</code>, or a folder with a board, <code>models.json</code> and its glTF models</span>
      </button>
    </div>
    <div class="samples">
      <h2>Or try a sample</h2>
      <div id="sample-cards" class="sample-cards">
        @for (sample of featured; track sample.id) {
          <button app-sample-card [sample]="sample" (click)="open.emit(sample)"></button>
        }
      </div>
      <div id="sample-chips" class="sample-cards sample-chips">
        @for (sample of handWritten; track sample.id) {
          <button app-sample-card [sample]="sample" (click)="open.emit(sample)"></button>
        }
      </div>
    </div>
    <!-- The IPC consortium test cases aren't part of the demo: links to the consortium's
         archives; the user downloads one and drops the named file from it here. -->
    <div class="samples">
      <h2>IPC consortium test data</h2>
      <p class="samples-hint">
        Download an archive from the <a [href]="testCasesPage">IPC-2581 Consortium</a>, then drop
        the file named on its card here.
      </p>
      <div id="test-case-links" class="sample-cards">
        @for (testCase of testCases; track testCase.id) {
          <a
            class="sample-card"
            [href]="testCase.url"
            target="_blank"
            rel="noopener"
            [title]="'Download the archive with ' + testCase.file + ' from the IPC-2581 Consortium'"
            [attr.data-test-case]="testCase.id"
          >
            <span class="sample-group">IPC consortium</span>
            <span class="sample-name">{{ testCase.name }}</span>
            <span class="sample-desc">
              {{ testCase.description }}
              <br />
              Open <code>{{ testCase.file }}</code> ({{ testCase.size }})
            </span>
            <span class="sample-size">ZIP ↓</span>
          </a>
        }
      </div>
    </div>
    <p class="footnote">
      boardui is open source (AGPL-3.0,
      <a href="https://github.com/midub/boardui/blob/master/LICENSING.md">commercial licence</a>
      available): <a href="https://github.com/midub/boardui">converter, viewer and profile spec</a>.
    </p>
  `,
})
export class Landing {
  readonly pickFile = output<void>();
  readonly open = output<Sample>();

  protected readonly featured = SAMPLES.filter((s) => s.group !== 'Hand-written');
  protected readonly handWritten = SAMPLES.filter((s) => s.group === 'Hand-written');
  protected readonly testCasesPage = TEST_CASES_PAGE;
  protected readonly testCases = TEST_CASES.map((testCase) => ({
    ...testCase,
    url: testCaseUrl(testCase),
    size: size(testCasePath(testCase)),
  }));
}

// packages/demo-react/src/Landing.tsx
import {
  formatBytes,
  SAMPLE_GROUPS,
  SAMPLES,
  type Sample,
  sampleLabel,
  TEST_CASES,
  TEST_CASES_PAGE,
  testCasePath,
  testCaseUrl,
} from '@boardui/demo-shared';
import { SAMPLE_SIZES } from '@boardui/demo-shared/sizes';
import type { ReactNode } from 'react';

const logo = `${import.meta.env.BASE_URL}logo.svg`;
const size = (path: string) => formatBytes(SAMPLE_SIZES[path] ?? 0);

/** The top bar's sample picker. */
export function SamplePicker({ onOpen }: { onOpen: (sample: Sample) => void }): ReactNode {
  return (
    <label className="sample-picker">
      <span className="sr-only">Sample board</span>
      <select
        id="sample-select"
        aria-label="Sample board"
        value=""
        onChange={(e) => {
          const sample = SAMPLES.find((s) => s.id === e.target.value);
          if (sample) onOpen(sample);
        }}
      >
        <option value="">Samples…</option>
        {SAMPLE_GROUPS.map((group) => (
          <optgroup key={group} label={group}>
            {SAMPLES.filter((s) => s.group === group).map((s) => (
              <option key={s.id} value={s.id}>
                {sampleLabel(s, SAMPLE_SIZES)}
              </option>
            ))}
          </optgroup>
        ))}
      </select>
    </label>
  );
}

function SampleCard({ sample, onOpen }: { sample: Sample; onOpen: () => void }): ReactNode {
  const featured = sample.group !== 'Hand-written';
  return (
    <button
      type="button"
      className={featured ? 'sample-card' : 'sample-chip'}
      data-sample={sample.id}
      title={sample.description}
      onClick={onOpen}
    >
      <span className="sample-group">{sample.group}</span>
      <span className="sample-name">{sample.name}</span>
      {featured && <span className="sample-desc">{sample.description}</span>}
      <span className="sample-size">{size(sample.xml)}</span>
    </button>
  );
}

/** The empty state: drop zone, samples, and links to the IPC consortium test cases. */
export function Landing({
  hidden,
  onPick,
  onOpen,
}: {
  hidden: boolean;
  onPick: () => void;
  onOpen: (sample: Sample) => void;
}): ReactNode {
  const card = (sample: Sample) => (
    <SampleCard key={sample.id} sample={sample} onOpen={() => onOpen(sample)} />
  );
  return (
    <div id="empty" className="empty" hidden={hidden}>
      <div className="hero">
        <img src={logo} alt="" width="72" height="72" />
        <h1>Printed circuit boards in 3D</h1>
        <p className="lead">
          Drop an <strong>IPC-2581</strong> file to convert it to a glTF board and explore its
          components, pins and nets. Conversion runs locally in WebAssembly: your file isn’t
          uploaded. 3D models of KiCad library parts are fetched from gitlab.com by footprint name.
        </p>
        <button id="drop-zone" className="drop-zone" type="button" onClick={onPick}>
          <span className="drop-title">Drop a file here, or click to choose one</span>
          <span className="drop-hint">
            IPC-2581 <code>.xml</code>, a boardui <code>.glb</code>, or a folder with a board,{' '}
            <code>models.json</code> and its glTF models
          </span>
        </button>
      </div>
      <div className="samples">
        <h2>Or try a sample</h2>
        <div id="sample-cards" className="sample-cards">
          {SAMPLES.filter((s) => s.group !== 'Hand-written').map(card)}
        </div>
        <div id="sample-chips" className="sample-cards sample-chips">
          {SAMPLES.filter((s) => s.group === 'Hand-written').map(card)}
        </div>
      </div>
      {/* The IPC consortium test cases aren't part of the demo: links to the consortium's
          archives; the user downloads one and drops the named file from it here. */}
      <div className="samples">
        <h2>IPC consortium test data</h2>
        <p className="samples-hint">
          Download an archive from the <a href={TEST_CASES_PAGE}>IPC-2581 Consortium</a>, then drop
          the file named on its card here.
        </p>
        <div id="test-case-links" className="sample-cards">
          {TEST_CASES.map((testCase) => (
            <a
              key={testCase.id}
              className="sample-card"
              href={testCaseUrl(testCase)}
              target="_blank"
              rel="noopener"
              title={`Download the archive with ${testCase.file} from the IPC-2581 Consortium`}
              data-test-case={testCase.id}
            >
              <span className="sample-group">IPC consortium</span>
              <span className="sample-name">{testCase.name}</span>
              <span className="sample-desc">
                {testCase.description}
                <br />
                Open <code>{testCase.file}</code> ({size(testCasePath(testCase))})
              </span>
              <span className="sample-size">ZIP ↓</span>
            </a>
          ))}
        </div>
      </div>
      <p className="footnote">
        boardui is open source (AGPL-3.0,{' '}
        <a href="https://github.com/midub/boardui/blob/master/LICENSING.md">commercial licence</a>{' '}
        available):{' '}
        <a href="https://github.com/midub/boardui">converter, viewer and profile spec</a>.
      </p>
    </div>
  );
}
