// packages/demo-angular/src/app/stats.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  inject,
  model,
  signal,
} from '@angular/core';
import { StatsMeter } from '@boardui/demo-shared';
import { session } from './session';

/** The `?stats` overlay: backend, frame rate, draw calls, triangles; and the spin toggle. */
@Component({
  selector: 'div[app-stats]',
  host: { id: 'stats', class: 'stats', '[attr.data-fps]': 'fps()' },
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <pre class="stats-text">{{ text() }}</pre>
    <label class="toggle">
      <input type="checkbox" id="spin-toggle" [checked]="spin()" (change)="onSpin($event)" />
      <span>spin</span>
    </label>
  `,
})
export class Stats {
  readonly spin = model.required<boolean>();
  protected readonly text = signal('');
  protected readonly fps = signal('0.0');

  constructor() {
    const meter = new StatsMeter();
    Object.assign(globalThis, { stats: meter });
    let frame = 0;
    const tick = (time: number) => {
      const next = meter.update(time, session.viewer?.stats() ?? null);
      if (next !== null) {
        this.text.set(next);
        this.fps.set(meter.fps.toFixed(1));
      }
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    inject(DestroyRef).onDestroy(() => cancelAnimationFrame(frame));
  }

  protected onSpin(event: Event): void {
    this.spin.set((event.target as HTMLInputElement).checked);
  }
}

// packages/demo-react/src/Stats.tsx
import { StatsMeter } from '@boardui/demo-shared';
import type { BoardViewerElement } from '@boardui/react';
import { type ReactNode, useEffect, useState } from 'react';

/** The `?stats` overlay: backend, frame rate, draw calls, triangles; and the spin toggle. */
export function Stats({
  viewer,
  spin,
  onSpin,
}: {
  /** The viewer (stable: the overlay measures from its first frame). */
  viewer: () => BoardViewerElement | null;
  spin: boolean;
  onSpin: (on: boolean) => void;
}): ReactNode {
  const [text, setText] = useState({ text: '', fps: '0.0' });
  useEffect(() => {
    const meter = new StatsMeter();
    Object.assign(globalThis, { stats: meter });
    let frame = 0;
    const tick = (time: number) => {
      const next = meter.update(time, viewer()?.stats() ?? null);
      if (next !== null) setText({ text: next, fps: meter.fps.toFixed(1) });
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [viewer]);
  return (
    <div id="stats" className="stats" data-fps={text.fps}>
      <pre className="stats-text">{text.text}</pre>
      <label className="toggle">
        <input
          type="checkbox"
          id="spin-toggle"
          checked={spin}
          onChange={(e) => onSpin(e.target.checked)}
        />
        <span>spin</span>
      </label>
    </div>
  );
}
